const stateConvertionMapping = {
    "JAMMU AND KASHMIR": "01",
    "HIMACHAL PRADESH": "02",
    PUNJAB: "03",
    CHANDIGARH: "04",
    UTTARANCHAL: "05",
    HARYANA: "06",
    DELHI: "07",
    RAJASTHAN: "08",
    "UTTAR PRADESH": "09",
    BIHAR: "10",
    SIKKIM: "11",
    "ARUNACHAL PRADESH": "12",
    NAGALAND: "13",
    MANIPUR: "14",
    MIZORAM: "15",
    TRIPURA: "16",
    MEGHALAYA: "17",  
    ASSAM: "18",
    "WEST BENGAL": "19",
    JHARKHAND: "20",
    ORISSA: "21",
    CHHATTISGARH: "22",
    "MADHYA PRADESH": "23",  
    GUJARAT: "24",
    "DAMAN AND DIU": "25",
    "DADRA AND NAGAR HAVELI AND DAMAN AND DIU": "26",  
    MAHARASHTRA: "27",
    "ANDHRA PRADESH": "28",
    KARNATAKA: "29",
    GOA: "30",
    LAKSHADWEEP: "31",
    KERALA: "32",
    "TAMIL NADU": "33",
    PONDICHERRY: "34",
    "ANDAMAN AND NICOBAR ISLANDS": "35",
    TELANGANA: "36",
    "APO ADDRESS": "99"
  };
  
  module.exports = {
    stateConvertionMapping
  };